<!-- 
// $name = "John";
// $age= 25;
// echo $name;
// ?> -->
<!-- // John -->

<!-- 
// $name= "David";
// $age= 25;
// echo $age;
?>
//25 -->
<!-- Constants are case Insensitive also this was written outside of 
< ? php

// define ("MSG", "<strong>Hi Demi!!!</strong>");
// echo MSG;
?> -->
<!-- 
// define('AGE', "28");
// echo "AGE";
// Notice: Use of undefined constant AGE - assumed 'AGE' in C:\xampp\htdocs\Monday PHP\Monday.PHP on line 21 -->


<!-- // define('AGE', "28");
// echo AGE; 
// Quotes were not needed.
// //28
// // ?> -->

<!-- 
// $str = "10";
// $int =  20;
// $sum = $str + $int;
// echo ($sum);
// 30 did not populate

// $someString ="15";
// $birthyear = 1982;
// echo $someString + birthyear;

// $name="David";
// function getNam(){
//     echo $name;

// }
// getName();

// Fatal error: Call to undefined function getName() in 
// C:\xampp\htdocs\Monday PHP\Monday.PHP on line 51
// cos The variable was not defined within the function

// $name="David";
// function getName(){
//     global$name;
//     echo$name;
// }
// getName();
// =David
//  -->

<!-- 
// $num1 = 56;
// function my_func(){
//     $num1 = 89;
//     echo $num1;
// }
// my_func();
 -->
<!-- 
// $a= "hello";
// $hello = "Hi!";
// echo $$a; -->

<?php
// $Hello = "World";
// $a = "Hello";
// echo $$a;
// ans= World cos it is a Variable Variable

// $x = "y";
// $y = "x";
// echo $$x;
// answer = x

// $num1 = 8;
// $num2 =6;
// echo $num1 + $num2;

// $num1= 23;
// $num2= 16;
// echo $num1 -$num2;
// =7

// $x = 14;
// $y = 3;
// echo $x% $y;
// =2 cos it is remainder of 14/3

// $num = 9;
// $num =$num%2;
// $num = 18;
// $num --;
// echo $num;


?>

